from tasks.parser import parse_tasks_markdown


SAMPLE = """# Tasks: Example Feature

**Input**: Design documents from `/specs/001-example/`

## Phase 1: Setup (Shared Infrastructure)

**Purpose**: Project initialization and basic structure

- [ ] T001 Create project structure per implementation plan
- [ ] T002 Initialize [language] project with [framework] dependencies
- [ ] T003 [P] Configure linting and formatting tools

---

## Phase 3: User Story 1 - Login (Priority: P1) \U0001F3AF MVP

**Goal**: Users can log in

### Tests for User Story 1

- [ ] T010 [P] [US1] Contract test for /login in tests/contract/test_login.py
- [x] T011 [P] [US1] Integration test for login flow in tests/integration/test_login.py

### Implementation for User Story 1

- [x] T012 [US1] Create User model in src/models/user.py

---

## Phase 6: Polish & Cross-Cutting Concerns

- [ ] T020 [P] Documentation updates in docs/
"""


def test_parses_task_key_checkbox_and_description():
    tasks = parse_tasks_markdown(SAMPLE)
    t001 = next(t for t in tasks if t["task_key"] == "T001")
    assert t001["description"] == "Create project structure per implementation plan"
    assert t001["checkbox_done"] is False
    assert t001["parallel"] is False
    assert t001["story"] is None


def test_parses_checked_checkbox_as_done():
    tasks = parse_tasks_markdown(SAMPLE)
    t012 = next(t for t in tasks if t["task_key"] == "T012")
    assert t012["checkbox_done"] is True


def test_parses_parallel_marker():
    tasks = parse_tasks_markdown(SAMPLE)
    t003 = next(t for t in tasks if t["task_key"] == "T003")
    assert t003["parallel"] is True
    assert t003["description"] == "Configure linting and formatting tools"


def test_parses_parallel_and_story_marker_together():
    tasks = parse_tasks_markdown(SAMPLE)
    t010 = next(t for t in tasks if t["task_key"] == "T010")
    assert t010["parallel"] is True
    assert t010["story"] == "US1"
    assert t010["description"] == "Contract test for /login in tests/contract/test_login.py"


def test_assigns_phase_from_enclosing_h2_heading_not_h3_subheadings():
    tasks = parse_tasks_markdown(SAMPLE)
    # T010/T011/T012 all fall under "### Tests for..." / "### Implementation
    # for..." H3 subheadings, but all belong to the SAME enclosing H2 phase.
    t010 = next(t for t in tasks if t["task_key"] == "T010")
    t012 = next(t for t in tasks if t["task_key"] == "T012")
    assert t010["phase"] == t012["phase"] == "Phase 3: User Story 1 - Login (Priority: P1) \U0001F3AF MVP"


def test_phase_order_increments_per_h2_heading_in_file_order():
    tasks = parse_tasks_markdown(SAMPLE)
    phase_orders = {t["phase"]: t["phase_order"] for t in tasks}
    assert phase_orders["Phase 1: Setup (Shared Infrastructure)"] == 0
    assert phase_orders["Phase 3: User Story 1 - Login (Priority: P1) \U0001F3AF MVP"] == 1
    assert phase_orders["Phase 6: Polish & Cross-Cutting Concerns"] == 2


def test_preserves_file_order():
    tasks = parse_tasks_markdown(SAMPLE)
    assert [t["task_key"] for t in tasks] == [
        "T001",
        "T002",
        "T003",
        "T010",
        "T011",
        "T012",
        "T020",
    ]


def test_empty_markdown_returns_no_tasks():
    assert parse_tasks_markdown("") == []


def test_markdown_with_no_tasks_returns_empty_list():
    assert parse_tasks_markdown("# Just a title\n\nSome prose, no tasks here.\n") == []


def test_parses_the_projects_own_real_tasks_md():
    """Regression against real, human-authored output (not just the
    template) - specs/001-documentation-agent/tasks.md, generated by this
    project's own /speckit.tasks run."""
    import os

    path = os.path.join(
        os.path.dirname(__file__), "..", "..", "specs", "001-documentation-agent", "tasks.md"
    )
    with open(path, encoding="utf-8") as f:
        content = f.read()

    tasks = parse_tasks_markdown(content)
    assert len(tasks) > 20
    t001 = next(t for t in tasks if t["task_key"] == "T001")
    assert t001["checkbox_done"] is True
    assert "extension package structure" in t001["description"]

    t012 = next(t for t in tasks if t["task_key"] == "T012")
    assert t012["parallel"] is True
    assert t012["story"] == "US1"
